"""Regenerate warpax_arxiv/paper_numbers.tex from cached analysis outputs.

Auto-sourced macros (vorticity fractions, NEC v_s-scaling coefficient, VdB
Type-I transition) are recomputed from ``results/*.json``; manually-maintained
macros (multi-file/derived provenance, e.g. the unconditional Eulerian miss
percentages and optimizer constants) are preserved from the existing file so the
generator never silently changes a hand-verified value.

Usage::

    python scripts/emit_paper_numbers.py
"""
from __future__ import annotations

import os
import re

from _paper_numbers_map import AUTO_SOURCED, MANUAL, recompute_auto

PAPER_NUMBERS = os.path.join(
    os.path.dirname(__file__), "..", "..", "warpax_arxiv", "paper_numbers.tex"
)

_MACRO_RE = re.compile(r"\\newcommand\{\\(\w+)\}\{([^}]*)\}")


def parse_macros(path: str) -> dict[str, str]:
    with open(path) as f:
        text = f.read()
    return {m.group(1): m.group(2) for m in _MACRO_RE.finditer(text)}


def main() -> int:
    existing = parse_macros(PAPER_NUMBERS)
    auto = recompute_auto()

    lines = [
        "%% paper_numbers.tex - numerical values cited in main.tex.",
        "%% Generated by scripts/emit_paper_numbers.py from results/*.json.",
        "%% Auto-sourced macros are recomputed; manually-maintained macros are",
        "%% preserved (see scripts/_paper_numbers_map.py).",
        "",
        "%% --- Manually maintained (derived / native-params) ---",
    ]
    for name, src in MANUAL.items():
        val = existing.get(name, "0")
        lines.append(f"\\newcommand{{\\{name}}}{{{val}}}  % {src}")
    lines += ["", "%% --- Auto-sourced from results/*.json ---"]
    for name, (_fn, _nd, src) in AUTO_SOURCED.items():
        lines.append(f"\\newcommand{{\\{name}}}{{{auto[name]}}}  % {src}")
    lines.append("")

    with open(PAPER_NUMBERS, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {PAPER_NUMBERS} "
          f"({len(MANUAL)} manual + {len(AUTO_SOURCED)} auto-sourced macros)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
