"""Rodal native-parameter missed-fraction stability across grid resolutions.

Recomputes the unconditional full-grid missed-violation fractions and total
violated fractions for the Rodal metric at its native parameters
(R = 100, sigma = 0.03, v_s = 0.5) at 25^3 / 50^3 / 100^3, backing the
resolution-stability table (Rodal is 100% Type I, so the robust truth is the
exact algebraic slack and the optimizer is bypassed).

Outputs
-------
- results/rodal_native_resolution.json
- ../warpax_arxiv/tables/rodal_resolution.tex

Usage
-----
    python scripts/run_rodal_native_resolution.py
"""
from __future__ import annotations

import os
import time
from datetime import datetime, timezone

from _json_io import dump_json

import jax

jax.config.update("jax_enable_x64", True)

import numpy as np

from warpax.analysis import compare_eulerian_vs_robust
from warpax.geometry import GridSpec, evaluate_curvature_grid
from warpax.metrics import RodalMetric

HERE = os.path.dirname(__file__)
RESULTS_DIR = os.path.join(HERE, "..", "results")
TABLES_DIR = os.path.join(HERE, "..", "..", "warpax_arxiv", "tables")

PARAMS = {"R": 100.0, "sigma": 0.03, "v_s": 0.5}
BOUNDS = [(-300, 300)] * 3
RESOLUTIONS = [25, 50, 100]
CONDITIONS = ("nec", "wec", "sec", "dec")


def analyze(N: int) -> dict:
    print(f"\n--- N = {N} ---")
    t0 = time.time()
    metric = RodalMetric(**PARAMS)
    grid_spec = GridSpec(bounds=BOUNDS, shape=(N, N, N))
    curv_batch = 256 if N <= 50 else 128
    opt_batch = 64 if N <= 50 else 16
    curv = evaluate_curvature_grid(metric, grid_spec, batch_size=curv_batch)
    comparison = compare_eulerian_vs_robust(
        curv.stress_energy,
        curv.metric,
        curv.metric_inv,
        grid_spec.shape,
        n_starts=8,
        batch_size=opt_batch,
    )
    row = {"N": N, "n_total": int(N**3)}
    for c in CONDITIONS:
        robust = np.asarray(comparison.robust_margins[c])
        row[f"{c}_missed"] = float(comparison.pct_missed[c])
        row[f"{c}_total"] = float(comparison.pct_violated_robust[c])
        row[f"{c}_min"] = float(np.nanmin(robust))
    row["elapsed_s"] = time.time() - t0
    print(
        "  missed: "
        + " ".join(f"{c}={row[f'{c}_missed']:.2f}" for c in CONDITIONS)
        + f"  ({row['elapsed_s']:.0f}s)"
    )
    return row


def emit_table(rows: list[dict]) -> None:
    lines = [
        "% Generated by scripts/run_rodal_native_resolution.py; do not edit.",
        "\\begin{tabular}{@{}r rrrr rrrr@{}}",
        "    \\toprule",
        "    & \\multicolumn{4}{c}{$f_{\\text{miss}}$ (\\%)} &",
        "      \\multicolumn{4}{c}{Total violated (\\%)} \\\\",
        "    \\cmidrule(lr){2-5} \\cmidrule(lr){6-9}",
        "    $N$ & NEC & WEC & SEC & DEC & NEC & WEC & SEC & DEC \\\\",
        "    \\midrule",
    ]
    for r in rows:
        mis = " & ".join(f"{r[f'{c}_missed']:.1f}" for c in CONDITIONS)
        tot = " & ".join(f"{r[f'{c}_total']:.1f}" for c in CONDITIONS)
        lines.append(f"    {r['N']:>4d} & {mis} & {tot} \\\\")
    lines += ["    \\bottomrule", "\\end{tabular}"]
    path = os.path.join(TABLES_DIR, "rodal_resolution.tex")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nWrote {os.path.normpath(path)}")


def main():
    os.makedirs(RESULTS_DIR, exist_ok=True)
    print("=" * 70)
    print("RODAL NATIVE-PARAMETER RESOLUTION STABILITY")
    print("=" * 70)
    rows = [analyze(N) for N in RESOLUTIONS]
    out = {
        "metadata": {
            "date": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "script": "scripts/run_rodal_native_resolution.py",
            "parameters": PARAMS,
            "bounds": BOUNDS,
            "resolutions": RESOLUTIONS,
            "n_starts": 8,
        },
        "per_resolution": rows,
    }
    path = os.path.join(RESULTS_DIR, "rodal_native_resolution.json")
    dump_json(out, path)
    print(f"Wrote {path}")
    emit_table(rows)


if __name__ == "__main__":
    main()
