"""Certified global enclosures of the wall null-energy deficit (paper Appendix H).

Answers the referee's request for a "global-coverage/error bound" to accompany the
basin-local continuum polishing of ``run_diagnostic_convergence.py``.

For each metric we run an interval-arithmetic Moore-Skelboe branch-and-bound over the
axisymmetry-reduced domain ``(x, s)``, ``s = sqrt(y^2 + z^2)``, and report

    lower <= inf_{wall} N <= upper,

where ``N(x) = min_{|v|=1} T_ab k^a k^b`` with ``k = n + v`` is the Eulerian-normalized
null deficit, which is defined at every point regardless of Hawking-Ellis type.

The two ends are not equally sharp. ``upper`` is an *achieved* value, evaluated on a
degenerate box with the same rigorous arithmetic, so it is a genuine wall value.
``lower`` is a continuum bound -- valid at every point, not merely at sampled ones,
which is the global statement local refinement cannot supply -- but it is loose,
because the interval extension of the full curvature chain overestimates. Report the
width; do not suppress it.

For an irrotational drive the Eulerian momentum vanishes identically, so
``N = min_i(rho + p_i)`` and the search reproduces the paper's polished invariant
margin by an independent route. For the vortical walls ``N`` is the all-type deficit
and is deeper than the Type-I-restricted margin, which samples only the residual
real-eigenvalue points.

Outputs
-------
- results/enclosures.json
- ../warpax_arxiv/tables/enclosures.tex
"""
from __future__ import annotations

import argparse
import math
import os
import time

from _json_io import dump_json

from warpax.energy_conditions.enclosure import (
    alcubierre_metric,
    certify_nec_deficit,
    natario_metric,
    rodal_metric,
    shape_interval,
    tail_bound,
    van_den_broeck_metric,
)

HERE = os.path.dirname(__file__)
RESULTS_DIR = os.path.join(HERE, "..", "results")
TABLES_DIR = os.path.join(HERE, "..", "..", "warpax_arxiv", "tables")

V_S, R_B, SIGMA = 0.5, 1.0, 8.0
BOX_X = (-3.0, 3.0)
BOX_S = (0.0, 3.0)
TAIL_X = (3.0, 30.0)
TAIL_S = (0.0, 30.0)

# Independently reported values for comparison. For Rodal (irrotational, b == 0)
# N is exactly the polished invariant margin min_i(rho + p_i) of
# run_diagnostic_convergence.py. For Alcubierre the wall is Type-IV dominated, so
# the Type-I-restricted margin is a different statistic; the comparable number is
# the all-wall NEC minimum quoted in the paper's per-metric section.
# value, and the statistic it is: the two are not the same quantity for every drive,
# and saying which is the whole point of the column.
REFERENCE = {
    "Alcubierre": (-0.628, r"all-wall NEC min, Sec.~3.3"),
    "Rodal": (-0.194, r"polished $\min(\rho+p_i)$"),
    # Natario and Van den Broeck have no directly comparable published statistic:
    # N is the all-type deficit, while the tabulated wall minima for these two are
    # restricted to their residual Type-I points. Left blank rather than compared
    # against a different quantity.
    "Natario": None,
    "VanDenBroeck": None,
}

# Van den Broeck's conformal parameters. Its shift is the same tanh top-hat as
# Alcubierre's, so the wall mask is unchanged; the slice carries B^2 delta_ij.
#
# R_tilde MUST match the benchmark, which fixes R_tilde = 1.0 everywhere else
# (run_velocity_sweep.py, run_diagnostic_convergence.py, run_matched_benchmark.py).
# It was 0.6 here, so the certified bracket in tables/enclosures.tex enclosed the
# extremum of a *different spacetime* from the one every other table reports, and
# the regression test in tests/test_enclosure.py compared the interval and JAX
# transcriptions of that same wrong instance -- agreeing with each other proves
# nothing about the metric the paper is about.
VDB_KW = dict(R_tilde=1.0, alpha_vdb=0.5, sigma_B=8.0)

BUILDERS = {
    "Alcubierre": alcubierre_metric,
    "Rodal": rodal_metric,
    "Natario": natario_metric,
    "VanDenBroeck": lambda v, R, s: van_den_broeck_metric(v, R, s, **VDB_KW),
}
ORDER = ["Alcubierre", "Rodal", "Natario", "VanDenBroeck"]


def _f(x, nd=4):
    return f"{x:.{nd}f}" if x is not None else "--"


def write_table(rows, out_path):
    lines = [
        "% Generated by scripts/run_enclosures.py; do not edit.",
        r"\begin{tabular}{@{}l cc c l@{}}",
        r"  \toprule",
        r"  Metric & $\mathcal{N}_{\rm lower}$ & $\mathcal{N}_{\rm upper}$ & width"
        r" & independently reported value \\",
        r"  \midrule",
    ]
    for name in ORDER:
        r = rows.get(name)
        if r is None:
            continue
        label = name.replace("VanDenBroeck", "Van den Broeck").replace(
            "Natario", "Nat\\'ario")
        ref = REFERENCE.get(name)
        ref_cell = f"${_f(ref[0], 3)}$ ({ref[1]})" if ref else "--"
        if not math.isfinite(r["lower"]):
            # Report non-closure explicitly rather than printing a bare -inf: a
            # bound that did not close is a coverage statement, not a number.
            lines.append(
                f"  {label} & \\multicolumn{{3}}{{c}}{{did not close at the box "
                f"budget}} & {ref_cell} \\\\"
            )
            continue
        lines.append(
            f"  {label} & ${_f(r['lower'],3)}$ & ${_f(r['upper'],4)}$ & "
            f"${r['width']:.1f}$ & {ref_cell} \\\\"
        )
    lines += [r"  \bottomrule", r"\end{tabular}"]
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"  Wrote {out_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tol", type=float, default=1e-4)
    ap.add_argument("--max-boxes", type=int, default=120000)
    ap.add_argument("--metrics", nargs="+", default=ORDER)
    args = ap.parse_args()

    print("=" * 72)
    print(f"CERTIFIED GLOBAL ENCLOSURES  (R_b={R_B}, sigma={SIGMA}, v_s={V_S})")
    print("=" * 72)

    rows = {}
    for name in args.metrics:
        t0 = time.time()
        metric = BUILDERS[name](V_S, R_B, SIGMA)
        shape = shape_interval(R_B, SIGMA)
        build_s = time.time() - t0
        t0 = time.time()
        enc = certify_nec_deficit(
            metric, shape, x_range=BOX_X, s_range=BOX_S,
            tol=args.tol, max_boxes=args.max_boxes,
        )
        search_s = time.time() - t0
        # The exterior is excluded because it holds no wall point, not because its
        # deficit is large: f depends on position only through r, so one interval
        # evaluation covers every direction, x < -3 included.
        tail_f_lo, tail_f_hi, tail_excluded = tail_bound(metric, shape, TAIL_X, TAIL_S)
        ref = REFERENCE.get(name)
        reference = ref[0] if ref else None
        rows[name] = {
            "lower": enc.lower,
            "upper": enc.upper,
            "width": enc.width,
            "argmin": list(enc.argmin),
            "n_evaluations": enc.n_evaluations,
            "tail_shape_enclosure": [tail_f_lo, tail_f_hi],
            "tail_excluded": tail_excluded,
            "reference": reference,
            "reference_statistic": ref[1] if ref else None,
            "build_seconds": build_s,
            "search_seconds": search_s,
        }
        print(
            f"  {name:12s} [{enc.lower:+.6f}, {enc.upper:+.6f}]  width={enc.width:.2e}  "
            f"evals={enc.n_evaluations}  build={build_s:.1f}s  search={search_s:.1f}s"
        )
        print(
            f"               argmin=({enc.argmin[0]:+.4f}, {enc.argmin[1]:+.4f})  "
            f"tail_lower={tail:+.4f}  tail_excluded={rows[name]['tail_excluded']}  "
            f"reference={reference}"
        )

    out = {
        "params": {
            "v_s": V_S, "R_b": R_B, "sigma": SIGMA,
            "box_x": list(BOX_X), "box_s": list(BOX_S),
            "tail_x": list(TAIL_X), "tail_s": list(TAIL_S),
            "tol": args.tol, "max_boxes": args.max_boxes,
            "wall_mask": [0.1, 0.9],
            "note": (
                "N = min_{|v|=1} (rho_n + 2 b.v + v^T S v), the Eulerian-normalized "
                "null deficit; defined at every point regardless of Hawking-Ellis type. "
                "Lower end certified on the continuum by interval branch-and-bound."
            ),
        },
        "order": [n for n in ORDER if n in rows],
        "results": rows,
    }
    dump_json(out, os.path.join(RESULTS_DIR, "enclosures.json"))
    print(f"\nWrote {os.path.join(RESULTS_DIR, 'enclosures.json')}")
    if all(n in rows for n in ORDER):
        write_table(rows, os.path.join(TABLES_DIR, "enclosures.tex"))


if __name__ == "__main__":
    main()
