"""Empirical speed fits of sampled Type-I wall NEC slacks.

The exact quadratic law requires zero momentum and a fixed comoving domain.
Alcubierre and Natario fits do not meet that premise. Their deviations may
reflect both momentum-dependent eigenvalues and sampling of a changing Type-I
subset; the two effects are not separated here. The integrated speed law is a
separate result. The SSV NEC conclusion has subsidiary hypotheses and supplies
no universal pointwise speed law.
"""

from __future__ import annotations

import json
import os

import numpy as np
from _json_io import dump_json

HERE = os.path.dirname(__file__)
RESULTS_DIR = os.path.join(HERE, "..", "results")
TABLES_DIR = os.path.join(HERE, "..", "..", "warpax_arxiv", "tables")

ORDER = ["Alcubierre", "Natário", "Van den Broeck", "Rodal"]


def _load(rel):
    with open(os.path.join(RESULTS_DIR, rel)) as f:
        return json.load(f)


def _subluminal_deficits(rows, metric):
    """Return (v_s, |min(rho+p_i)|, n_type_i) for violating Type-I wall points."""
    vs, def_, n_i = [], [], []
    for r in rows:
        if r["metric"] != metric or r["v_s"] >= 1.0:
            continue
        nec = r.get("typeI_nec_min")
        if nec is None or not np.isfinite(nec) or nec >= 0.0:
            continue
        if r.get("n_type_i_wall", 0) < 1:
            continue
        vs.append(r["v_s"])
        def_.append(abs(nec))
        n_i.append(int(r["n_type_i_wall"]))
    order = np.argsort(vs)
    return np.array(vs)[order], np.array(def_)[order], np.array(n_i)[order]


# A second empirical fit window; this cutoff does not separate numerical and physical effects.
DENSE_VS = 0.5


def fit_bound(vs, deficits, n_type_i=None):
    """Fixed-exponent (q=2) velocity fit + free-exponent check.

    Fixed model: deficit = C v_s^2, least squares through the origin in v_s^2,
    so C = sum(deficit * v_s^2) / sum(v_s^4). Also report the free log-log
    exponent q and both R^2, plus the worst relative deviation of the data from
    the fixed-exponent fit.
    """
    if len(vs) < 3:
        return {
            "C": None,
            "r_squared_fixed": None,
            "q_free": None,
            "r_squared_free": None,
            "max_rel_dev": None,
            "max_rel_dev_dense": None,
            "n_type_i_min": None,
            "n": len(vs),
        }
    v2 = vs**2
    C = float(np.sum(deficits * v2) / np.sum(v2**2))
    pred = C * v2
    ss_res = float(np.sum((deficits - pred) ** 2))
    # Through-origin fit (deficit = C v_s^2, no intercept): use the uncentered
    # total sum of squares; the table defines this uncentered R^2 explicitly.
    ss_tot = float(np.sum(deficits**2))
    r2_fixed = 1.0 - ss_res / ss_tot if ss_tot > 0 else 1.0
    rel_dev = np.abs(deficits - pred) / np.abs(deficits)
    max_rel_dev = float(np.max(rel_dev))
    dense = vs >= DENSE_VS
    max_rel_dev_dense = float(np.max(rel_dev[dense])) if dense.any() else None
    # Free exponent (log-log) for an independent check that q ~ 2.
    lv, ld = np.log(vs), np.log(deficits)
    q, logA = np.polyfit(lv, ld, 1)
    pred_l = q * lv + logA
    ss_res_l = float(np.sum((ld - pred_l) ** 2))
    ss_tot_l = float(np.sum((ld - np.mean(ld)) ** 2))
    r2_free = 1.0 - ss_res_l / ss_tot_l if ss_tot_l > 0 else 1.0
    # An additional empirical two-term fit; D is not an exact momentum coefficient.
    A = np.vstack([v2, vs]).T
    (C2, D), *_ = np.linalg.lstsq(A, deficits, rcond=None)
    pred2 = A @ np.array([C2, D])
    r2_two = 1.0 - float(np.sum((deficits - pred2) ** 2)) / ss_tot if ss_tot > 0 else 1.0
    return {
        "C": C,
        "r_squared_fixed": float(r2_fixed),
        "q_free": float(q),
        "r_squared_free": float(r2_free),
        "max_rel_dev": max_rel_dev,
        "max_rel_dev_dense": max_rel_dev_dense,
        "dense_v_s_min": DENSE_VS,
        "n_type_i_min": int(np.min(n_type_i)) if n_type_i is not None else None,
        "n_type_i_max": int(np.max(n_type_i)) if n_type_i is not None else None,
        "C_two": float(C2),
        "D_two": float(D),
        "r_squared_two": float(r2_two),
        "n": len(vs),
    }


def _f(x, nd=3):
    return f"{x:.{nd}f}" if (x is not None and np.isfinite(x)) else "--"


def write_table(fits, out_path):
    lines = [
        r"% Generated by scripts/run_ssv_bound.py from results/velocity_sweep.json;"
        r" do not edit.",
        r"\begin{tabular}{@{}l ccccc@{}}",
        r"  \toprule",
        r"  Metric & $C$ & dev.\ (all $v_s$) & dev.\ ($v_s\ge0.5$) & $R^2$"
        r" & NEC at sampled $v_s$ \\",
        r"  \midrule",
    ]

    def _pct(x):
        return f"{x * 100:.2f}\\%" if (x is not None and np.isfinite(x)) else "--"

    for name in ORDER:
        fit = fits[name]
        r2 = fit.get("r_squared_fixed")
        sign = "violated" if fit["nec_violated_at_all_sampled_speeds"] else "not uniform"
        if r2 is not None and np.isfinite(r2) and r2 >= 0.99 and fit.get("C", 0):
            lines.append(
                f"  {name} & {_f(fit.get('C'))} & {_pct(fit.get('max_rel_dev'))} & "
                f"{_pct(fit.get('max_rel_dev_dense'))} & "
                f"{_f(fit.get('r_squared_fixed'), 4)} & {sign} \\\\"
            )
        else:
            # The gate is R^2 >= 0.99, not the existence of Type-I points: Van den
            # Broeck has a Type-I branch, it just admits no single power law.
            lines.append(
                rf"  {name} & \multicolumn{{4}}{{c}}{{no adequate quadratic fit "
                rf"($R^2={_f(r2, 2)}$)}} & {sign} \\"
            )
    lines += [r"  \bottomrule", r"\end{tabular}"]
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Wrote {out_path}")


def main():
    sweep = _load("velocity_sweep.json")
    rows = sweep["rows"]

    print("=" * 70)
    print("WALL NEC DEFICIT SPEED SCALING  min(rho+p_i) = -C v_s^2")
    print("=" * 70)
    fits = {}
    for name in ORDER:
        vs, deficits, n_type_i = _subluminal_deficits(rows, name)
        fit = fit_bound(vs, deficits, n_type_i)
        sampled = [row for row in rows if row["metric"] == name]
        fit["sign_test_speeds"] = [row["v_s"] for row in sampled]
        fit["nec_violated_at_all_sampled_speeds"] = bool(sampled) and all(
            row["wall_frac_type_iv"] > 0
            or (row.get("typeI_nec_min") is not None and row["typeI_nec_min"] < 0)
            for row in sampled
        )
        fits[name] = fit
        print(
            f"  {name:16s} C={_f(fit['C'])}  q_free={_f(fit['q_free'], 2)}  "
            f"R^2={_f(fit['r_squared_fixed'], 4)}  "
            f"maxdev={_f((fit['max_rel_dev'] or float('nan')) * 100, 2)}%  "
            f"dev(v_s>={DENSE_VS})="
            f"{_f((fit['max_rel_dev_dense'] or float('nan')) * 100, 2)}%  "
            f"n_typeI={fit['n_type_i_min']}..{fit['n_type_i_max']}  "
            f"n={fit['n']}"
        )

    out = {
        "model": "empirical fixed-exponent fit min(rho+p_i) = -C v_s^2",
        "exact_scope": "quadratic form only when j=0 on a fixed comoving domain; C is numerical",
        "r_squared_definition": "uncentered: 1-sum((y-C*v_s^2)^2)/sum(y^2)",
        # Provenance: this fit reads the velocity sweep, so it is only as current as
        # the sweep is. Recording the sweep's own config here makes a stale rerun
        # visible in the artifact instead of only in a file mtime.
        "source": {"file": "velocity_sweep.json", "config": sweep.get("config")},
        "fits": fits,
    }
    out_path = os.path.join(RESULTS_DIR, "ssv_bound.json")
    dump_json(out, out_path)
    print(f"\nWrote {out_path}")
    write_table(fits, os.path.join(TABLES_DIR, "ssv_bound.tex"))


if __name__ == "__main__":
    main()
